Repository FEC-Wall-E/RFE-2303-FEC, pull requests merged in 2023-05, with the labels that each got.

#2 added dependencies
  package-lock.json
  package.json
Labels: enhancement

#4 added all our components
  client/src/App.jsx
  client/src/Product.jsx
  client/src/Store.jsx
  client/src/index.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/Outfits/Outfit.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/RR/RR.jsx
Labels: enhancement

#5 working on routes
  client/src/App.jsx
  client/src/index.jsx
  client/src/widgets/Outfits/Outfit.jsx
  package-lock.json
  package.json
  server/helpers.js
  server/index.js
Labels: enhancement

#6 finished routes with team on live share
  client/src/App.jsx
  server/helpers.js
  server/index.js
Labels: enhancement

#7 added initial props
  client/src/Product.jsx
  client/src/Store.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/RR/RR.jsx
Labels: enhancement

#13 built out questionlist component
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  server/helpers.js
Labels: enhancement

#17 initialized tests and implemented modal skeleton
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionModal.jsx
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#20 Completed question modal functionality
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/QuestionModal.jsx
Labels: enhancement

#21 Sub-component files created and set up
  client/src/widgets/RR/NewReview.jsx
  client/src/widgets/RR/ProductBreakdown.jsx
  client/src/widgets/RR/RR.jsx
  client/src/widgets/RR/RatingBreakdown.jsx
  client/src/widgets/RR/ReviewTile.jsx
  client/src/widgets/RR/ReviewsList.jsx
  client/src/widgets/RR/Sort.jsx
Labels: enhancement

#24 added example test for question modal
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/QuestionModal.jsx
Labels: enhancement

#25 created basic answer component
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/Question.jsx
Labels: enhancement

#38 can mark questions as helpful. fixing bug in photo upload
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerModal.jsx
  client/src/widgets/QA/PhotoModal.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
Labels: enhancement

#41 can mark answers as helpful
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/Question.jsx
Labels: enhancement

#44 fixed photo modal
  client/src/widgets/QA/AnswerModal.jsx
  client/src/widgets/QA/PhotoModal.jsx
Labels: enhancement

#45 answer reporting works
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/Question.jsx
Labels: enhancement

#46 can expand question list and collapse it
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/QuestionList.jsx
Labels: enhancement

#50 added answer list display and question search bar
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionSearch.jsx
Labels: enhancement

#51 fixed search bug, works now
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionSearch.jsx
Labels: enhancement

#56 added tests for photo modal, minor css changes
  client/src/widgets/QA/PhotoModal.jsx
  client/src/widgets/QA/PhotoModal.test.js
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionSearch.jsx
  package-lock.json
  package.json
Labels: enhancement

#62 review photos zoom in on click
  client/src/widgets/QA/Answer.jsx
Labels: enhancement

#64 changed css for question, answer and QA photo modals
  client/src/widgets/QA/AnswerModal.jsx
  client/src/widgets/QA/PhotoModal.jsx
  client/src/widgets/QA/QuestionModal.jsx
Labels: enhancement

#65 Small additions
  client/src/Product.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/OV/ProductInfo.jsx
  server/helpers.js
Labels: bug, enhancement

#68 Fixed bug so now questions and answers match current product
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/QuestionList.jsx
  server/helpers.js
Labels: bug, enhancement

#70 added a checkmark and border
  client/src/widgets/OV/Gallery.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/OV/Style.jsx
  client/src/widgets/OV/StyleSelector.jsx
Labels: enhancement

#75 Question search now searches all questions, not just displayed 4 questions
  client/src/widgets/QA/QuestionList.jsx
Labels: bug

#76 added photo modal to photos displayed in answer
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerPhotoModal.jsx
Labels: enhancement

#81 successfully stubbed axios get request in test
  client/src/widgets/QA/QA.test.js
Labels: enhancement

#82 default gallery view meets business doc reqs
  client/src/widgets/OV/Gallery.jsx
  client/src/widgets/OV/GalleryCarousel.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/OV/Photos/GalleryPhoto.jsx
  client/src/widgets/OV/Photos/MainGalleryPhoto.jsx
Labels: bug, enhancement

#88 CSS changes
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/AnswerModal.jsx
  client/src/widgets/QA/AnswerModal.test.js
  client/src/widgets/QA/AnswerPhotoModal.jsx
  client/src/widgets/QA/PhotoModal.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/QA.test.js
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionModal.jsx
  client/src/widgets/QA/QuestionSearch.jsx
Labels: enhancement

#103 small css changes + ratings bug fix
  client/dist/OVstyles.css
  client/src/widgets/OV/Photos/ExtendedGalleryPhoto.jsx
  client/src/widgets/OV/ProductInfo.jsx
  client/src/widgets/OV/Style.jsx
Labels: bug

#106 added interactions and button borders
  client/src/widgets/QA/Answer.jsx
  client/src/widgets/QA/AnswerList.jsx
  client/src/widgets/QA/AnswerModal.jsx
  client/src/widgets/QA/PhotoModal.jsx
  client/src/widgets/QA/QA.jsx
  client/src/widgets/QA/Question.jsx
  client/src/widgets/QA/QuestionList.jsx
  client/src/widgets/QA/QuestionModal.jsx
Labels: enhancement

#120 matched fonts
  client/src/widgets/QA/QA.jsx
Labels: enhancement

#122 worked on readme
  README copy.md
  README.md
  images/AddReview.png
  images/ProjectOverview.png
  images/Questions.png
  images/QuestionsAnswers.png
  images/RelatedProducts.png
  images/Reviews.png
  server/index.js
Labels: documentation

#123 State
  README.md
  client/src/widgets/OV/AddToCart.jsx
  client/src/widgets/OV/Overview.jsx
  client/src/widgets/OV/ProductInfo.jsx
  client/src/widgets/OV/Tests/Overview.test.js
  client/src/widgets/PostAPIInteraction.jsx
  client/src/widgets/RR/NewReview.jsx
  client/src/widgets/RR/ReviewTile.jsx
Labels: documentation
